import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { Box } from "@mui/material";
import { CartProvider } from "./context/CartContext";
import Footer from "./components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Box sx={{ m: 0, p: 0 }}>
          <CartProvider>
            <Navbar />
            <Box sx={{ pt: 10 }}> 
              {children}
            </Box>
            <Footer />
          </CartProvider>
        </Box>
      </body>
    </html>
  );
}
